/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package programmenu1;

/**
 *
 * @author Administrator
 */
public class HargaHotel extends javax.swing.JInternalFrame {
    class nama_p extends HargaHotel{
        String nama = txtnama.getText();
    }
    /**
     * Creates new form HargaHOtel
     */
    public HargaHotel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        outNP = new javax.swing.JLabel();
        outTK = new javax.swing.JLabel();
        outLM = new javax.swing.JLabel();
        outTH = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        txtLM = new javax.swing.JTextField();
        kombo = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Harga Hotel Wonderful Indramayu");

        jLabel2.setText("Nama Pengunjung");

        jLabel3.setText("Tipe Kamar");

        jLabel4.setText("Lama Menginap");

        jLabel5.setText("Nama Pengunjung");

        jLabel6.setText("Tipe Kamar");

        jLabel7.setText("Lama Menginap");

        jLabel8.setText("Total Harga");

        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });

        txtLM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLMActionPerformed(evt);
            }
        });

        kombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Premium", "Deluxe", "Superior" }));

        jLabel13.setText("Hari");

        jButton1.setText("Kirim");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnama)
                            .addComponent(outNP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(outTK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(outLM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtLM)
                                    .addComponent(kombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(outTH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(kombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtLM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jButton1))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(outNP, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(outTK, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(outLM, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addComponent(outTH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        nama_p satu=new nama_p();
        String tipekamar = kombo.getSelectedItem().toString();
        int hari,harga;
        hari= Integer.parseInt(txtLM.getText());
        
        if(tipekamar == "Superior"){
            if(hari<=2){
                harga= 100000;
                outNP.setText(satu.nama);
                outTK.setText(tipekamar);
                outLM.setText(String.valueOf(hari));
                int harga_a=harga*hari;
                outTH.setText(String.valueOf(harga_a));
            } else if (hari<=4){
                harga= 90000;
                outNP.setText(satu.nama);
                outTK.setText(tipekamar);
                outLM.setText(String.valueOf(hari));
                int harga_a=harga*hari;
                outTH.setText(String.valueOf(harga_a));
            } else {
                harga= 80000;
                outNP.setText(satu.nama);
                outTK.setText(tipekamar);
                outLM.setText(String.valueOf(hari));
                int harga_a=harga*hari;
                outTH.setText(String.valueOf(harga_a));
            }
        } else if (tipekamar == "Deluxe"){
            if(hari<=2){
                harga= 150000;
                outNP.setText(satu.nama);
                outTK.setText(tipekamar);
                outLM.setText(String.valueOf(hari));
                int harga_a=harga*hari;
                outTH.setText(String.valueOf(harga_a));
            } else if (hari<=4){
                harga= 135000;
                outNP.setText(satu.nama);
                outTK.setText(tipekamar);
                outLM.setText(String.valueOf(hari));
                int harga_a=harga*hari;
                outTH.setText(String.valueOf(harga_a));
            } else {
                harga= 120000;
                outNP.setText(satu.nama);
                outTK.setText(tipekamar);
                outLM.setText(String.valueOf(hari));
                int harga_a=harga*hari;
                outTH.setText(String.valueOf(harga_a));
            }
        } else if (tipekamar == "Premium"){ 
            if(hari<=2){
                harga= 200000;
                outNP.setText(satu.nama);
                outTK.setText(tipekamar);
                outLM.setText(String.valueOf(hari));
                int harga_a=harga*hari;
                outTH.setText(String.valueOf(harga_a));
            } else if (hari<=4){
                harga= 180000;
                outNP.setText(satu.nama);
                outTK.setText(tipekamar);
                outLM.setText(String.valueOf(hari));
                int harga_a=harga*hari;
                outTH.setText(String.valueOf(harga_a));
            } else {
                harga= 160000;
                outNP.setText(satu.nama);
                outTK.setText(tipekamar);
                outLM.setText(String.valueOf(hari));
                int harga_a=harga*hari;
                outTH.setText(String.valueOf(harga_a));
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtLMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLMActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JComboBox<String> kombo;
    private javax.swing.JLabel outLM;
    private javax.swing.JLabel outNP;
    private javax.swing.JLabel outTH;
    private javax.swing.JLabel outTK;
    private javax.swing.JTextField txtLM;
    private javax.swing.JTextField txtnama;
    // End of variables declaration//GEN-END:variables
}
